sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t iporat08/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iporat08/docker-react npm run test
