version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  tests: #a second container for tests which will reference our local tests
        build:
          context: .
          dockerfile: Dockerfile.dev
        volumes:
          - /app/node_modules
          - .:/app
        command: ["npm","run","test"] #override the starting command of the test
